### ISSUE TITLE
Error on platformIO

### ISSUE THREAD

**Issue by fyouda** [c010rblind3ngineer/CantTouchThisVer2#1]
'class WiFiClient' has no member named 'setTrustAnchors'

**Comment by c010rblind3ngineer** [comment]
@fyouda do you have this library installed? -> https://arduino.esp8266.com/stable/package_esp8266com_index.json

**Comment by fyouda** [comment]
Yes thank I found the problem and it was stupid i apologize for wasting your time

**Comment by c010rblind3ngineer** [comment]
@fyouda No worries! Thanks for pointing it out :)
